# Buildar aplicação
FROM node:24-alpine AS builder

WORKDIR /app
COPY package*.json ./
COPY pnpm*.yaml ./

RUN npm install -g pnpm@11.5.2 && pnpm install --frozen-lockfile
COPY . .

RUN pnpm run build

RUN pnpm prune --production

# Rodar aplicação
FROM node:24-alpine AS runner
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/main.js"]